seed: ${seed}
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}
sparse: ${model.sparse}

num_workers: 8

# fraction of data to use (needs to be supported by dataset):
event_frac: 1.0
train_frac: 0.8
test_frac: 0.1

# optional scale factors for features/coords
transform_features: False
features_loc: null
features_scale: null

transform_coords: False
coords_loc: null
coords_scale: null

# the semantic labels that should be ignored when clustering (needs to be supported by clusterer) and in embed criterion (needs to be supported by embed criterion)
cluster_ignore_labels: null
# the semantic label that should be ignored in semantic segmentation criterion (needs to be supported by semantic criterion)
semantic_ignore_label: -100

# the dimension that contains batch information (only relevant if sparse=False)
batch_dim: 0

# required fields (set to null if not relevant to dataset):
num_classes: ???
num_features: ???
voxel_size: ???
data_dir: ???