defaults:
  - base_dataset
_target_: calo_cluster.datasets.hcal_Zll_jets.HCalZllJetsDataModule

# required fields:
num_classes: 2
num_features: 5
voxel_size: 0.1

# dataset-specific fields (should not change):
noise_id: -99
cluster_ignore_labels: [0,]
semantic_label: pf_hit
instance_label: PFcluster0Id
weight: energy


# data location (modify as needed):
data_dir: ${data_dir}/hcal/Zll_jets
raw_data_dir: ${data_dir}/hcal/Zll_jets/min_energy_0.0_min_hits_0

# config fields:
feats: ['x', 'y', 'z', 'time', 'energy']
coords: ['x', 'y', 'z']
min_hits_per_cluster: 0
min_cluster_energy: 0.0
min_eta: null
max_eta: null
instance_target: pf

transform_coords: True
coords_loc: [-2.2650774,  0.9025515, -5.4258814]
coords_scale: [ 89.17557,  90.16204, 404.67374]