defaults:
  - base_dataset
_target_: calo_cluster.datasets.hgcal.HGCalDataModule

# required fields:
num_classes: 4
num_features: 5
voxel_size: 0.05

# dataset-specific fields (should not change):

# data location (modify as needed):
data_dir: ${data_dir}/hgcal
download: True

# config fields:
noise_level: 1.0
